### ISSUE TITLE
Issue with using GET instead of POST

### ISSUE THREAD

**Issue by explodecomputer** [MRCIEU/opengwas-api#14]
https://github.com/MRCIEU/opengwas-api/blob/e67041c2263d9cff87d64a15c2f650200e32fc82/app/apis/tophits.py#L46

Hey @JasonQiu just a quick point that sometimes the number of IDs requested can be very long, meaning that they will exceed the maximum url length. This is true for a number of end points, so in general the ieugwasr package uses POST for query rather than GET. Is it possible to stick with this?

**Comment by JasonQiu** [comment]
Hi @explodecomputer, the original POST implementation had been in OCI prod, but since we updated reverse proxy to redirect users to OCI prod, the API Gateway has been logging '405 Method Not Allowed', i.e. no change to POST implementation, no change to ieugwasr, just applied 302, and we get 405 error on API Gateway.

To address this issue - I once changed it to GET and pushed to prod, but realised it is not working either, so finally reset to POST.

I logged onto mr-base-api-v3_mr-base-api-v3-public_1 (which runs the latest version without any of my commits) and checked tophits.py - it seems like our old in-house prod has POST implementation, as expected. (https://github.com/MRCIEU/opengwas-api/commit/66ef1d07a5e0266583e20d8d487e6f43044f4214)

So I'm still trying to figure our why the same POST implementation does not behave as expected on OCI. I suspect that it has something to do with the flask-restx (a breaking upgrade from flask-restplus). It definitely passed all the local unit tests (and all the playground requests made in Swagger docs work well, both locally and in OCI prod), but obviously it is not compatible with either ieugwasr or the way it is served by API Gateway, or both(?). Still need more time (and a few updates & reverts on reverse proxy!).

**Comment by JasonQiu** [comment]
Access log from API Gateway:
```
{
  "datetime": 1711320260445,
  "logContent": {
    "data": {
      "bodyBytesSent": 64,
      "gatewayId": "ocid1.apigateway.oc1.uk-london-1.xxxxxxxxxx",
      "httpUserAgent": "libcurl/7.64.1 r-curl/4.3.2 httr/1.4.7",
      "message": "GET /api/tophits HTTP/1.1",
      "opcRequestId": "/0ADD3B83BF97D81A6EFC8DFB37F520AB/B130A9FD4A2CC6613E0683098336CEF6",
      "remoteAddr": "61.157.16.2",
      "requestDuration": 0.007,
      "requestMethod": "GET",
      "requestUri": "/api/tophits",
      "serverProtocol": "HTTP/1.1",
      "status": 405
    },
    "id": "0db690c3-ea30-11ee-b4a7-c8fe2a87e359",
    "oracle": {
      "compartmentid": "ocid1.compartment.oc1..xxxxxxxxxx",
      "ingestedtime": "2024-03-24T22:45:31.475Z",
      "loggroupid": "ocid1.loggroup.oc1.uk-london-1.xxxxxxxxxx",
      "logid": "ocid1.log.oc1.uk-london-1.xxxxxxxxxx",
      "tenantid": "ocid1.tenancy.oc1..xxxxxxxxxx"
    },
    "source": "api",
    "specversion": "1.0",
    "time": "2024-03-24T22:44:20.445Z",
    "type": "com.oraclecloud.apigateway.apideployment.access"
  },
  "regionId": "uk-london-1"
}
```

"httpUserAgent": "libcurl/7.64.1 r-curl/4.3.2 httr/1.4.7",
"message": "GET /api/tophits HTTP/1.1",
"requestMethod": "GET",
 "status": 405

Need to check why ieugwasr is sending GET, while /tophits only accepts POST. Might have something to do with curl and httr and their behaviour. Pre-flight request?

**Comment by JasonQiu** [comment]
https://stackoverflow.com/a/30076527


> You're following redirects, that means you get a 3xx response code and curl makes a second request to the new URL.

> curl will act according to the specific 3xx code and for some of the redirects it will change request method from POST to GET
